### ISSUE TITLE
libSkiaSharp.so

### ISSUE THREAD

**Issue by brianbostw** [oshogbo/fbsd-fnaify#1]
Hello, trying to use fnaify with Stardew Valley. I am getting an error that libSkiaSharp.so can not be found. Unfortunately I do not see this lib in FreeBSD's pkg repos.

`+ echo 'The following requirements were not met:'
The following requirements were not met:
+ [ 0 -eq 1 ]
+ [ -z 'libSkiaSharp.so ' ]
+ echo ''

+ exit 1`

**Comment by oshogbo** [comment]
Can you provide some more details?
Which version of fnaify are you using from this repo or official one?
Which version of FreeBSD?
Which version of the game?

**Comment by rfht** [comment]
that file can be ignored based on my experience on OpenBSD, see https://github.com/rfht/fnaify/blob/master/fnaify#L179. It was added in recent versions.

A simple quick fix should be to just 

```
$ rm lib{,64}/libSkiaSharp.so*
```
and then just run `fnaify` again.

By the way lots has happened in the last 18 months on [upstream fnaify](https://github.com/rfht/fnaify), most notably addition of a long list of XNA games. I haven't tested it on FreeBSD lately, but would like to aspire to help fix any compatibility issues with FreeBSD that may have been introduced.

**Comment by brianbostw** [comment]
Removing libSkiaSharp.dll from data/noarch/game/ worked. I am on FreeBSD 12.1-RELEASE and game version 1_4_5_433754439_36068 successfully launched. I'll check out the other games on the list and if I have any of them report back to you my findings when I get around to playing them. Thanks!

**Comment by rfht** [comment]
@beastwick feel free to open an issue on https://github.com/rfht/fnaify/issues if you should find that the current version runs into unexpected problems on FreeBSD.
